version: "3.8"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    ports:
      - 5432:5432
    volumes:
    - pgdata:/data/postgres
  app:
    restart: always
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app



volumes:
  pgdata:
    driver: local